name: Release Web Assembly

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release WebAssembly
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [bundler, nodejs, web, no-modules]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build WebAssembly for ${{ matrix.target }}
        run: |
          cd wasm
          wasm-pack build --release --target ${{ matrix.target }}

      - name: Release WebAssembly for ${{ matrix.target }}
        uses: actions/upload-artifact@v4
        with:
          name: wasm-package-${{ matrix.target }}
          path: wasm/pkg
